## Data Structure:-
i)list<br>
ii)dictonary<br>
iii)tuple<br>
iv)set<br>

### List:-[],mutable,orderded,

In [3]:
lst=['shivanshu','rahul','bhanu','yogesh']
print(lst)

['shivanshu', 'rahul', 'bhanu', 'yogesh']

In [ ]:
lst=[12,34,53,14]
print(lst)
print(len(lst))
sum(lst)
max(lst)
min(lst)

[12, 34, 53, 14]
4

## dictonary:-{},key values pair,mutable,unordered collection

In [18]:
dict={"name:-":"Shivanshu","course:-":"B.Tech","RollNO:-":34}
print(dict)
print(type(dict))
print(dict["name:-"])
dict['Skills']="Python"
print(dict)
# print(name)

{'name:-': 'Shivanshu', 'course:-': 'B.Tech', 'RollNO:-': 34}
<class 'dict'>
Shivanshu
{'name:-': 'Shivanshu', 'course:-': 'B.Tech', 'RollNO:-': 34, 'Skills': 'Python'}

In [24]:
print(dict.keys())
print(dict.values())

dict_keys(['name:-', 'course:-', 'RollNO:-'])
dict_values(['Shivanshu', 'B.Tech', 34])

How to find in python library:- one cmd are use
help('modules')

In [8]:
! pip install pandas

Requirement already satisfied: pandas in d:\tca_datascience\envi\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\tca_datascience\envi\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\tca_datascience\envi\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\tca_datascience\envi\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in d:\tca_datascience\envi\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd

In [10]:
# rollno=[101,102,103,104,105,106]
# names=['Raman','Aman','Amar','Manav']
# course=['BCA','MCA','BBA','M.Tech']
# df=pd.DataFrame({"RollNo":rollno,"Name":names,"Course":course})
# df

In [27]:
help('modules')

Please wait a moment while I gather a list of all available modules...

test_sqlite3: testing with version '2.6.0', sqlite_version '3.42.0'

d:\TCA_DataScience\envi\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

IPython             _warnings           html                sched
__future__          _weakref            http                secrets
__hello__           _weakrefset         idlelib             select
__phello__          _winapi             imaplib             selectors
_abc                _xxsubinterpreters  imghdr              setuptools
_aix_support        _zoneinfo           imp                 shelve
_ast                abc                 importlib           shlex
_asyncio            aifc                inspect             shutil
_bisect             antigravity         io                  signal
_blake2             argparse            ipaddress           site
_bootsubprocess     array               ipykernel           six
_bz2                ast                 ipykernel_launcher  smtpd
_codecs             asttokens           ipython_pygments_lexers smtplib
_codecs_cn          asynchat            itertools           sndhdr
_codecs_hk          asyncio             jedi                socket
_codecs_iso2022     asyncore            json                socketserver
_codecs_jp          atexit              jupyter             sqlite3
_codecs_kr          audioop             jupyter_client      sre_compile
_codecs_tw          base64              jupyter_core        sre_constants
_collections        bdb                 keyword             sre_parse
_collections_abc    binascii            lib2to3             ssl
_compat_pickle      bisect              linecache           stack_data
_compression        builtins            locale              stat
_contextvars        bz2                 logging             statistics
_csv                cProfile            lzma                string
_ctypes             calendar            mailbox             stringprep
_ctypes_test        cgi                 mailcap             struct
_datetime           cgitb               marshal             subprocess
_decimal            chunk               math                sunau
_distutils_hack     cmath               matplotlib_inline   symtable
_elementtree        cmd                 mimetypes           sys
_functools          code                mmap                sysconfig
_hashlib            codecs              modulefinder        tabnanny
_heapq              codeop              msilib              tarfile
_imp                collections         msvcrt              telnetlib
_io                 colorama            multiprocessing     tempfile
_json               colorsys            nest_asyncio        test
_locale             comm                netrc               textwrap
_lsprof             compileall          nntplib             this
_lzma               concurrent          nt                  threading
_markupbase         configparser        ntpath              time
_md5                contextlib          nturl2path          timeit
_msi                contextvars         numbers             tkinter
_multibytecodec     copy                numpy               token
_multiprocessing    copyreg             opcode              tokenize
_opcode             crypt               operator            tomllib
_operator           csv                 optparse            tornado
_osx_support        ctypes              os                  trace
_overlapped         curses              packaging           traceback
_pickle             dataclasses         pandas              tracemalloc
_py_abc             datetime            parso               traitlets
_pydecimal          dateutil            pathlib             tty
_pyio               dbm                 pdb                 turtle
_queue              debugpy             pickle              turtledemo
_random             decimal             pickletools         types
_sha1               decorator           pip                 typing
_sha256             difflib             pipes               typing_extensions
_sha3               dis                 pkg_resources       tzdata
_sha512             distutils           pkgutil             unicodedata
_signal             doctest             platform            unittest
_sitebuiltins       email               platformdirs        urllib
_socket             encodings           plistlib            uu
_sqlite3            ensurepip           poplib              uuid
_sre                enum                posixpath           venv
_ssl                errno               pprint              warnings
_stat               executing           profile             wave
_statistics         faulthandler        prompt_toolkit      wcwidth
_string             filecmp             pstats              weakref
_strptime           fileinput           psutil              webbrowser
_struct             fnmatch             pty                 winreg
_symtable           fractions           pure_eval           winsound
_testbuffer         ftplib              py_compile          wsgiref
_testcapi           functools           pyclbr              xdrlib
_testconsole        gc                  pydoc               xml
_testimportmultiple genericpath         pydoc_data          xmlrpc
_testinternalcapi   getopt              pyexpat             xxsubtype
_testmultiphase     getpass             pygments            zipapp
_thread             gettext             queue               zipfile
_threading_local    glob                quopri              zipimport
_tkinter            graphlib            random              zlib
_tokenize           gzip                re                  zmq
_tracemalloc        hashlib             reprlib             zoneinfo
_typing             heapq               rlcompleter
_uuid               hmac                runpy

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

In [13]:
! pip install openpyxl

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 435.7 kB/s eta 0:00:01
   --------- ----------------------------- 61.4/250.9 kB 550.5 kB/s eta 0:00:01
   ----------------- -------------------- 112.6/250.9 kB 656.4 kB/s eta 0:00:01
   ------------------ ------------------- 122.9/250.9 kB 654.9 kB/s eta 0:00:01
   ----------------------------- -------- 194.6/250.9 kB 737.3 kB/s eta 0:00:01
   -------------------------------------  245.8/250.9 kB 793.0 kB/s eta 0:00:01
   -------------------------------------- 250.9/250.9 kB 771.4 kB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
pd.read_excel(r"D:\TCA_DataScience\Day1\myData.xlsx")

,Order ID,Order Date,Customer ID,Customer Name,Address,City,State,ZIP/Postal Code,Country/Region,Salesperson,...,Shipper Name,Ship Name,Ship Address,Ship City,Payment Type,Product Name,Category,Unit Price,Quantity,Sales
0,1001,2014-01-27,27,Company AA,789 27th Street,Las Vegas,NV,99999,USA,Mariya Sergienko,...,Shipping Company B,Karen Toh,789 27th Street,Las Vegas,Check,Beer,Beverages,14.0,49,686.0
1,1002,2014-01-27,27,Company AA,789 27th Street,Las Vegas,NV,99999,USA,Mariya Sergienko,...,Shipping Company B,Karen Toh,789 27th Street,Las Vegas,Check,Dried Plums,Dried Fruit & Nuts,3.5,55,192.5
2,1003,2014-01-04,4,Company D,123 4th Street,New York,NY,99999,USA,Andrew Cencini,...,Shipping Company A,Christina Lee,123 4th Street,New York,Credit Card,Dried Pears,Dried Fruit & Nuts,30.0,22,660.0
3,1003,2014-01-04,4,Company D,123 4th Street,New York,NY,99999,USA,Andrew Cencini,...,Shipping Company A,Christina Lee,123 4th Street,New York,Credit Card,Dried Pears,Dried Fruit & Nuts,30.0,22,660.0
4,1003,2014-01-04,4,Company D,123 4th Street,New York,NY,99999,USA,Andrew Cencini,...,Shipping Company A,Christina Lee,123 4th Street,New York,Credit Card,Dried Pears,Dried Fruit & Nuts,30.0,22,660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,1067,2014-03-08,8,Company H,123 8th Street,Portland,OR,99999,USA,Nancy Freehafer,...,Shipping Company C,Elizabeth Andersen,123 8th Street,Portland,Credit Card,Mozzarella,Dairy Products,34.8,63,2192.4
382,1070,2014-03-03,3,Company C,123 3rd Street,Los Angelas,CA,99999,USA,Mariya Sergienko,...,Shipping Company B,Thomas Axerr,123 3rd Street,Los Angelas,Cash,Syrup,Condiments,10.0,48,480.0
383,1071,2014-03-03,3,Company C,123 3rd Street,Los Angelas,CA,99999,USA,Mariya Sergienko,...,Shipping Company B,Thomas Axerr,123 3rd Street,Los Angelas,Cash,Curry Sauce,Sauces,40.0,71,2840.0
384,1075,2014-03-10,10,Company J,123 10th Street,Chicago,IL,99999,USA,Laura Giussani,...,Shipping Company B,Roland Wacker,123 10th Street,Chicago,Credit Card,Almonds,Dried Fruit & Nuts,10.0,55,550.0
385,1077,2014-03-10,10,Company J,123 10th Street,Chicago,IL,99999,USA,Laura Giussani,...,Shipping Company A,Roland Wacker,123 10th Street,Chicago,Cash,Dried Plums,Dried Fruit & Nuts,3.5,21,73.5

In [15]:
pd.read_excel(r"D:\TCA_DataScience\Day1\myData.xlsx",sheet_name="Sheet2")

   Order ID  Product Category  Amount        State
0      P001  Carrots      Veg     1238      Haryana
1      P002  Carrots    Fruit     1776       Punjab
2      P003  Banana     Fruit     1138         Asam
3      P003  Banana     Fruit     1138         Asam
4      P004   Potato      Veg     1972  Uttarakhand
5      P005   Tomato      Veg     3456      Haryana
6      P006   Beans       Veg     4298       Punjab
7      P007  Carrots    Fruit     3666         Asam
8      P008  Carrots      Veg     4192  Uttarakhand
9      P008  Carrots      Veg     4192  Uttarakhand
10     P009   Tomato    Fruit     3363      Haryana
11     P010  Banana     Fruit     4380       Punjab
12     P011   Potato      Veg     3917         Asam
13     P012   Tomato      Veg     2263  Uttarakhand
14     P013   Beans       Veg     1042      Haryana
15     P014   Tomato    Fruit     4093       Punjab
16     P015  Carrots      Veg     2240         Asam
17     P007  Carrots    Fruit     3666      Haryana
18     P008  Carrots      Veg     4192       Punjab
19     P009   Tomato    Fruit     3363      Haryana
20     P010  Banana     Fruit     4380       Punjab
21     P011   Potato      Veg     3917         Asam
22     P012   Tomato      Veg     2263  Uttarakhand
23     P013   Beans       Veg     1042  Uttarakhand
24     P014   Tomato    Fruit     4093         Asam
25     P015  Carrots      Veg     2240      Haryana
26     P016  Banana     Fruit     1042       Punjab
27     P017   Potato      Veg     4093         Asam
28     P018   Tomato      Veg     2240  Uttarakhand
29     P019   Beans       Veg     3666  Uttarakhand
30     P020   Tomato    Fruit     4192         Asam
31     P021  Carrots      Veg     3363      Haryana
32     P022  Banana     Fruit     4380       Punjab
33     P023  Banana     Fruit     3917       Punjab
34     P024   Potato      Veg     1042         Asam
35     P025   Tomato      Veg     4093  Uttarakhand
36     P026   Beans       Veg     2240  Uttarakhand
37     P027   Tomato    Fruit     3666         Asam

In [17]:
df=pd.read_excel(r"D:\TCA_DataScience\Day1\myData.xlsx",sheet_name="Sheet3")

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SID       14 non-null     str
 1   Std_Name  14 non-null     str
 2   Eng       13 non-null     float64
 3   Math      13 non-null     float64
 4   Hindi     13 non-null     float64
 5   Result    13 non-null     str
dtypes: float64(3), str(3)
memory usage: 948.0 bytes

## set:-unordered,unindexed,mutuable

In [1]:
set1={1,2,3,4,5,7,9}
set1

{1, 2, 3, 4, 5, 7, 9}

In [3]:
set1.add(6)
set1

{1, 2, 3, 4, 5, 6, 7, 9}

In [5]:
set2={3,5,2,14,51}
set1.update(set2)
set1

{1, 2, 3, 4, 5, 6, 7, 9, 14, 51}

In [6]:
set2

{2, 3, 5, 14, 51}